### PR TITLE
feat: show publish date on --verbose

### LINKED ISSUE #419: `--verbose` should show publish dates
**Is your feature request related to a problem? Please describe.**

We ask customers to run `sf version --verbose` when creating an issue. When looking at that information, it's not obvious to the customer if they're behind latest and, if so, how far behind they are. 

Essentially, we'd like to make it easy for the customer to realize that they're behind latest. Obviously, plugin-warn-if-update-available serves the same purpose but it can be disabled or easily ignored. 

**Describe the solution you'd like**
- `version --verbose` shows the publish date, the number of days old the CLI version is, and what latest is under `CLI Version`
- `version --verbose` shows the publish date and what latest is of user-installed plugins under `Plugin Version`

For example

```
 CLI Version:
	@salesforce/cli/2.37.4 (Published 4/10/2024 - 3 weeks ago. Latest is 2.39.6)

 Architecture:
	darwin-arm64

 Node Version:
	node-v20.11.0

 Plugin Version:
	@oclif/plugin-autocomplete 3.0.13 (core)
	@oclif/plugin-commands 3.2.2 (core)
	@oclif/plugin-help 6.0.20 (core)
	@oclif/plugin-not-found 3.1.2 (core)
	@oclif/plugin-plugins 5.0.7 (core)
	@oclif/plugin-search 1.0.20 (core)
	@oclif/plugin-update 4.2.4 (core)
	@oclif/plugin-version 2.0.16 (core)
	@oclif/plugin-warn-if-update-available 3.0.15 (core)
	@oclif/plugin-which 3.1.7 (core)
	@salesforce/cli 2.37.4 (core)
	apex 3.1.4 (core)
	auth 3.5.5 (core)
	data 3.2.5 (core)
	deploy-retrieve 3.5.6 (core)
	info 3.1.3 (core)
	limits 3.2.1 (core)
	marketplace 1.1.1 (core)
	org 4.0.4 (core)
	packaging 2.3.0 (core)
	schema 3.2.1 (core)
	settings 2.1.2 (core)
	sobject 1.2.2 (core)
	source 3.2.3 (core)
	telemetry 3.1.18 (core)
	templates 56.1.1 (core)
	trust 3.5.4 (core)
	user 3.4.3 (core)
	sfdmu 4.33.12 (user) (published 4/25/2024, latest is 4.33.17)
```

**Describe alternatives you've considered**
`@oclif/plugin-warn-if-update-available` serves a similar purpose but it can be disabled and/or easily missed by the user.

### PR DESCRIPTION
**Pull request by mdonnalley**
- Show publish dates and latest when using `--verbose`
- Bold headers
- Dim plugin info

**Before**

Screenshot 2024-05-07 at 10 09 59 AM

**After**

Screenshot 2024-05-07 at 10 09 43 AM

Fixes #419 
@W-15664257@

### CODE REVIEW

**Comment by mshanemc** [comment]
QA: 

sf plugins link this into `sf`
✅ it's clear my CLI is not `latest`
✅ a very old user plugin shows that it was public 942 days ago. 😄 

📓 `@salesforce/cli/2.41.4 published 13 days ago (Tue Apr 23 2024) (latest is 2.39.6)` 
I think I'm ok with this being red?  I'm usually on nightly but most people probably aren't.  

❓ how do you feel about this PR changing the `--json` output?  

[downgrade to stable, user-install plugin-org to yesterday's release]
✅ warnings
✅ no warning here `org 4.1.8 (user) published 1 days ago (Mon May 06 2024)`

[switch to an older plugin-org]
❌   org 4.0.1 (user) published 1 days ago (Mon May 06 2024) (latest is 4.1.8) <-- that's the wrong date for that version

[uninstall plugin-org and install via `sf plugins install https://github.com/salesforcecli/plugin-org`]
✅ in this case, pjson version on `main` is correct because that's latest?  

[uninstall plugin-org and install via `sf plugins install https://github.com/salesforcecli/plugin-org#341c60ac3514c436aa8a1fd7431703e622c88ae4`]
❌ `org 3.5.1 (user) published 1 days ago (Mon May 06 2024) (latest is 4.1.8)` that's definitely a wrong datestamp for when that version happened.

❓ if oclif officially supports "install from gh" should those **appear** different in `sf plugins` or `sf version`.

**Review by mshanemc — CHANGES_REQUESTED** [review]
see qa notes

**Comment by mdonnalley** [comment]
>❓ how do you feel about this PR changing the --json output?

I suspect that few people are depending on the json output here, especially since it's not easy to work with (It's just the human readable output put into a json array). If you think we should major version, then I'd recommend switching to a more usable json output, e.g. `{name: org, type: user, version: 3.5.1}` instead of `org 3.5.1 (user)`. 

>❓ if oclif officially supports "install from gh" should those appear different in sf plugins or sf version.

I could go either way but I'm leaning towards waiting until someone asks for it

**Review by mshanemc — APPROVED** [review]

**Comment by mshanemc** [comment]
QA notes:
✅  dates are correct now for npm and gh based installs

**Pull request merged**
